# Generated by Django 4.0.5 on 2022-06-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_profile_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighbourhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood'),
        ),
    ]
