# Generated by Django 4.0.5 on 2022-06-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
