# Generated by Django 4.0.5 on 2022-06-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_neighbourhood_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood'),
        ),
    ]
