# Generated by Django 4.0.5 on 2022-06-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_neighbourhood_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
